repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(juman_grammar|lib)/
      - id: trailing-whitespace
        exclude: ^lib/
      - id: check-yaml
      - id: check-added-large-files

  #  - repo: https://github.com/pre-commit/mirrors-eslint
  #    rev: v8.41.0  # Use the sha / tag you want to point at
  #    hooks:
  #    -   id: eslint

  #  - repo: https://github.com/pre-commit/mirrors-csslint
  #    rev: v1.0.5
  #    hooks:
  #    - id: csslint
  #      files: \.css$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--write, --ignore-path, .prettierignore]
#  - repo: https://github.com/scop/pre-commit-perlcritic
#    rev: v1.150-1
#    hooks:
#      - id: perlcritic
